<a href="https://colab.research.google.com/github/chiyanglin-AStar/Python_AI/blob/main/supervised_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

simplest linear regression example with python Ex1:

In [ ]:
# prompt: please give simplest linear regression example without scikitlearn

# Import the necessary libraries

import numpy as np

# Create some data
X = np.array([[1], [2], [3], [4]])
y = np.array([2, 4, 6, 8])

# Calculate the means of X and y
mean_x = np.mean(X)
mean_y = np.mean(y)

# Calculate the numerator and denominator of the slope
num = 0
den = 0
for i in range(len(X)):
  num += (X[i] - mean_x) * (y[i] - mean_y)
  den += (X[i] - mean_x) ** 2

# Calculate the slope and intercept
slope = num / den
intercept = mean_y - slope * mean_x

# Make predictions
y_pred = slope * X + intercept

# Print the predictions
print(y_pred)


[[2.]
 [4.]
 [6.]
 [8.]]


simplest linear regression example with python Ex2:

In [ ]:
def predict(x, m, b):
  return m * x + b

# Create some data
X = np.array([1, 2, 3, 4])
y = np.array([2, 4, 6, 8])

# Initialize the parameters
m = 0
b = 0

# Perform gradient descent
for i in range(1000):
  # Calculate the gradients
  y_predicted = predict(X, m, b)
  gradient_m = -2 * np.sum(X * (y - y_predicted))
  gradient_b = -2 * np.sum(y - y_predicted)

  # Update the parameters
  m -= 0.01 * gradient_m
  b -= 0.01 * gradient_b

# Make predictions
X_test = np.array([5])
y_pred = predict(X_test, m, b)

# Print the predictions
print(y_pred)


[9.9999975]


simplest linear regression example with python Ex3:

In [ ]:
# prompt: please give simplest linear regression example without scikitlearn

# Create a simple dataset
X = np.array([[1], [2], [3], [4]])
y = np.array([2, 4, 6, 8])

# Calculate the means of X and y
mean_x = np.mean(X)
mean_y = np.mean(y)

# Calculate the slope of the regression line
slope = np.sum((X - mean_x) * (y - mean_y)) / np.sum((X - mean_x) ** 2)

# Calculate the intercept of the regression line
intercept = mean_y - slope * mean_x

# Make predictions
y_pred = slope * X + intercept

# Print the predictions
print(y_pred)


[[5.]
 [5.]
 [5.]
 [5.]]


simplest linear regression example with python Ex4:

In [ ]:
# prompt: please give simplest linear regression example without scikitlearn

# Import the necessary libraries

import numpy as np

# Create some data
X = np.array([[1], [2], [3], [4]])
y = np.array([2, 4, 6, 8])

# Calculate the means of X and y
mean_x = np.mean(X)
mean_y = np.mean(y)

# Calculate the numerator and denominator of the slope
num = 0
den = 0
for i in range(len(X)):
  num += (X[i] - mean_x) * (y[i] - mean_y)
  den += (X[i] - mean_x) ** 2

# Calculate the slope and intercept
slope = num / den
intercept = mean_y - slope * mean_x

# Make predictions
y_pred = slope * X + intercept

# Print the predictions
print(y_pred)

[[2.]
 [4.]
 [6.]
 [8.]]


simplest Supervised Learning example with python Ex1:

In [ ]:
# prompt: can give simplest Supervised Learning example with python

# Import the necessary libraries
import numpy as np
from sklearn.linear_model import LinearRegression

# Create some data
X = np.array([[1], [2], [3], [4]])
y = np.array([2, 4, 6, 8])

# Create a linear regression model
model = LinearRegression()

# Train the model
model.fit(X, y)

# Make predictions
y_pred = model.predict([[5]])

# Print the predictions
print(y_pred)

[10.]


simplest Supervised Learning example with python Ex2:

In [ ]:
# prompt: can give simplest Supervised Learning example with python

import numpy as np
from sklearn.linear_model import LinearRegression

# Create a simple dataset
X = np.array([[1], [2], [3], [4]])
y = np.array([2, 4, 6, 8])

# Train the linear regression model
model = LinearRegression()
model.fit(X, y)

# Make predictions
y_pred = model.predict(np.array([[5], [6]]))

# Print the predictions
print(y_pred)

[10. 12.]


simplest Supervised Learning example with python Ex3:

In [ ]:
# prompt: can give simplest Supervised Learning example with python

# Import the necessary libraries
from sklearn.linear_model import LinearRegression

# Create a linear regression model
model = LinearRegression()

# Prepare the training data
X_train = [[1], [2], [3], [4]]
y_train = [2, 4, 6, 8]

# Train the model
model.fit(X_train, y_train)

# Make predictions
X_test = [[5]]
y_pred = model.predict(X_test)

# Print the predictions
print(y_pred)

[10.]


simplest Supervised Learning example with python Ex4:

In [ ]:
# prompt: can give simplest Supervised Learning example with python

# Import the necessary libraries
from sklearn.linear_model import LinearRegression

# Create a linear regression model
model = LinearRegression()

# Prepare the training data
X = [[1], [2], [3], [4]]
y = [2, 4, 6, 8]

# Train the model
model.fit(X, y)

# Prepare the test data
X_test = [[5]]

# Predict the output for the test data
y_predicted = model.predict(X_test)

# Print the predicted output
print(y_predicted)


[10.]


In [ ]:
# prompt: please give simplest linear regression example without scikitlearn

import numpy as np

# Create a simple dataset
X = np.array([[1], [2], [3], [4]])
y = np.array([2, 4, 6, 8])

# Calculate the mean of X and y
mean_x = np.mean(X)
mean_y = np.mean(y)

# Calculate the slope of the regression line
m = np.sum((X - mean_x) * (y - mean_y)) / np.sum((X - mean_x) ** 2)

# Calculate the y-intercept of the regression line
b = mean_y - m * mean_x

# Print the slope and y-intercept
print("Slope:", m)
print("Y-intercept:", b)

# Make predictions
X_test = np.array([[5]])
y_pred = m * X_test + b

# Print the predictions
print("Predictions:", y_pred)


Slope: 0.0
Y-intercept: 5.0
Predictions: [[5.]]


### Prompt: Certainly! Here's a simple example of linear regression using Python without any external frameworks:

In this example, we first generate some random data with a linear relationship. Then, we use the normal equation to find the optimal parameters (theta) for the linear regression model. Finally, we plot the original data and the fitted regression line.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Generate some random data for demonstration
np.random.seed(42)
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1)

# Plot the generated data
plt.scatter(X, y)
plt.xlabel('X')
plt.ylabel('y')
plt.title('Generated Data for Linear Regression')
plt.show()

# Add bias term to X
X_b = np.c_[np.ones((100, 1)), X]

# Use the normal equation to find the best fit parameters (theta)
theta_best = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

# Print the obtained parameters
print("Theta (intercept, slope):", theta_best.flatten())

# Make predictions using the obtained parameters
X_new = np.array([[0], [2]])
X_new_b = np.c_[np.ones((2, 1)), X_new]
y_predict = X_new_b.dot(theta_best)

# Plot the original data and the regression line
plt.plot(X_new, y_predict, "r-", label="Predictions")
plt.scatter(X, y, label="Original Data")
plt.xlabel('X')
plt.ylabel('y')
plt.title('Linear Regression with the Fitted Line')
plt.legend()
plt.show()


### Prompt: Certainly! Here's a simple example of linear regression using Python without any external frameworks:

Certainly! Linear regression is a simple algorithm for predicting a continuous outcome variable based on one or more predictor variables. Here's a basic example of linear regression using Python without any frameworks:

In this example, we manually calculate the slope (m) and intercept (b) using the least squares method. The linear regression equation Y = mX + b is then used to predict the outcome variable for a new value of the predictor variable (new_X).

In [ ]:
# Simple Linear Regression Example without any framework

# Sample data
X = [1, 2, 3, 4, 5]  # Predictor variable
Y = [2, 4, 5, 4, 5]  # Outcome variable

# Calculate mean of X and Y
mean_X = sum(X) / len(X)
mean_Y = sum(Y) / len(Y)

# Calculate slope (m) and intercept (b)
numerator = sum((xi - mean_X) * (yi - mean_Y) for xi, yi in zip(X, Y))
denominator = sum((xi - mean_X)**2 for xi in X)

m = numerator / denominator  # Slope
b = mean_Y - m * mean_X  # Intercept

# Predict using the linear regression equation: Y = mX + b
new_X = 6
predicted_Y = m * new_X + b

# Print the results
print(f"Slope (m): {m}")
print(f"Intercept (b): {b}")
print(f"Predicted Y for X={new_X}: {predicted_Y}")
