<a href="https://colab.research.google.com/github/chiyanglin-AStar/Python_AI/blob/main/supervised_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

simplest Supervised Learning example with python Ex1:

In [1]:
# prompt: can give simplest Supervised Learning example with python

# Import the necessary libraries
import numpy as np
from sklearn.linear_model import LinearRegression

# Create some data
X = np.array([[1], [2], [3], [4]])
y = np.array([2, 4, 6, 8])

# Create a linear regression model
model = LinearRegression()

# Train the model
model.fit(X, y)

# Make predictions
y_pred = model.predict([[5]])

# Print the predictions
print(y_pred)

[10.]


simplest Supervised Learning example with python Ex2:

In [2]:
# prompt: can give simplest Supervised Learning example with python

import numpy as np
from sklearn.linear_model import LinearRegression

# Create a simple dataset
X = np.array([[1], [2], [3], [4]])
y = np.array([2, 4, 6, 8])

# Train the linear regression model
model = LinearRegression()
model.fit(X, y)

# Make predictions
y_pred = model.predict(np.array([[5], [6]]))

# Print the predictions
print(y_pred)

[10. 12.]


simplest Supervised Learning example with python Ex3:

In [3]:
# prompt: can give simplest Supervised Learning example with python

# Import the necessary libraries
from sklearn.linear_model import LinearRegression

# Create a linear regression model
model = LinearRegression()

# Prepare the training data
X_train = [[1], [2], [3], [4]]
y_train = [2, 4, 6, 8]

# Train the model
model.fit(X_train, y_train)

# Make predictions
X_test = [[5]]
y_pred = model.predict(X_test)

# Print the predictions
print(y_pred)

[10.]


simplest Supervised Learning example with python Ex4:

In [4]:
# prompt: can give simplest Supervised Learning example with python

# Import the necessary libraries
from sklearn.linear_model import LinearRegression

# Create a linear regression model
model = LinearRegression()

# Prepare the training data
X = [[1], [2], [3], [4]]
y = [2, 4, 6, 8]

# Train the model
model.fit(X, y)

# Prepare the test data
X_test = [[5]]

# Predict the output for the test data
y_predicted = model.predict(X_test)

# Print the predicted output
print(y_predicted)


[10.]


In [5]:
# prompt: please give simplest linear regression example without scikitlearn

# Import the necessary libraries

import numpy as np

# Create some data
X = np.array([[1], [2], [3], [4]])
y = np.array([2, 4, 6, 8])

# Calculate the means of X and y
mean_x = np.mean(X)
mean_y = np.mean(y)

# Calculate the numerator and denominator of the slope
num = 0
den = 0
for i in range(len(X)):
  num += (X[i] - mean_x) * (y[i] - mean_y)
  den += (X[i] - mean_x) ** 2

# Calculate the slope and intercept
slope = num / den
intercept = mean_y - slope * mean_x

# Make predictions
y_pred = slope * X + intercept

# Print the predictions
print(y_pred)


[[2.]
 [4.]
 [6.]
 [8.]]


In [6]:
def predict(x, m, b):
  return m * x + b

# Create some data
X = np.array([1, 2, 3, 4])
y = np.array([2, 4, 6, 8])

# Initialize the parameters
m = 0
b = 0

# Perform gradient descent
for i in range(1000):
  # Calculate the gradients
  y_predicted = predict(X, m, b)
  gradient_m = -2 * np.sum(X * (y - y_predicted))
  gradient_b = -2 * np.sum(y - y_predicted)

  # Update the parameters
  m -= 0.01 * gradient_m
  b -= 0.01 * gradient_b

# Make predictions
X_test = np.array([5])
y_pred = predict(X_test, m, b)

# Print the predictions
print(y_pred)


[9.9999975]


In [7]:
# prompt: please give simplest linear regression example without scikitlearn

import numpy as np

# Create a simple dataset
X = np.array([[1], [2], [3], [4]])
y = np.array([2, 4, 6, 8])

# Calculate the mean of X and y
mean_x = np.mean(X)
mean_y = np.mean(y)

# Calculate the slope of the regression line
m = np.sum((X - mean_x) * (y - mean_y)) / np.sum((X - mean_x) ** 2)

# Calculate the y-intercept of the regression line
b = mean_y - m * mean_x

# Print the slope and y-intercept
print("Slope:", m)
print("Y-intercept:", b)

# Make predictions
X_test = np.array([[5]])
y_pred = m * X_test + b

# Print the predictions
print("Predictions:", y_pred)


Slope: 0.0
Y-intercept: 5.0
Predictions: [[5.]]


In [8]:
# prompt: please give simplest linear regression example without scikitlearn

# Create a simple dataset
X = np.array([[1], [2], [3], [4]])
y = np.array([2, 4, 6, 8])

# Calculate the means of X and y
mean_x = np.mean(X)
mean_y = np.mean(y)

# Calculate the slope of the regression line
slope = np.sum((X - mean_x) * (y - mean_y)) / np.sum((X - mean_x) ** 2)

# Calculate the intercept of the regression line
intercept = mean_y - slope * mean_x

# Make predictions
y_pred = slope * X + intercept

# Print the predictions
print(y_pred)


[[5.]
 [5.]
 [5.]
 [5.]]


In [9]:
# prompt: please give simplest linear regression example without scikitlearn

# Import the necessary libraries

import numpy as np

# Create some data
X = np.array([[1], [2], [3], [4]])
y = np.array([2, 4, 6, 8])

# Calculate the means of X and y
mean_x = np.mean(X)
mean_y = np.mean(y)

# Calculate the numerator and denominator of the slope
num = 0
den = 0
for i in range(len(X)):
  num += (X[i] - mean_x) * (y[i] - mean_y)
  den += (X[i] - mean_x) ** 2

# Calculate the slope and intercept
slope = num / den
intercept = mean_y - slope * mean_x

# Make predictions
y_pred = slope * X + intercept

# Print the predictions
print(y_pred)

[[2.]
 [4.]
 [6.]
 [8.]]
